################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2dulpx/iis2dulpx.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2dulpx/iis2dulpx_reg.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2mdc/iis2mdc.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2mdc/iis2mdc_reg.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ilps22qs/ilps22qs.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ilps22qs/ilps22qs_reg.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism330is/ism330is.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism330is/ism330is_reg.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism6hg256x/ism6hg256x.c \
C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism6hg256x/ism6hg256x_reg.c 

OBJS += \
./Drivers/BSP/Components/iis2dulpx.o \
./Drivers/BSP/Components/iis2dulpx_reg.o \
./Drivers/BSP/Components/iis2mdc.o \
./Drivers/BSP/Components/iis2mdc_reg.o \
./Drivers/BSP/Components/ilps22qs.o \
./Drivers/BSP/Components/ilps22qs_reg.o \
./Drivers/BSP/Components/ism330is.o \
./Drivers/BSP/Components/ism330is_reg.o \
./Drivers/BSP/Components/ism6hg256x.o \
./Drivers/BSP/Components/ism6hg256x_reg.o 

C_DEPS += \
./Drivers/BSP/Components/iis2dulpx.d \
./Drivers/BSP/Components/iis2dulpx_reg.d \
./Drivers/BSP/Components/iis2mdc.d \
./Drivers/BSP/Components/iis2mdc_reg.d \
./Drivers/BSP/Components/ilps22qs.d \
./Drivers/BSP/Components/ilps22qs_reg.d \
./Drivers/BSP/Components/ism330is.d \
./Drivers/BSP/Components/ism330is_reg.d \
./Drivers/BSP/Components/ism6hg256x.d \
./Drivers/BSP/Components/ism6hg256x_reg.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/iis2dulpx.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2dulpx/iis2dulpx.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/iis2dulpx_reg.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2dulpx/iis2dulpx_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/iis2mdc.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2mdc/iis2mdc.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/iis2mdc_reg.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/iis2mdc/iis2mdc_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ilps22qs.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ilps22qs/ilps22qs.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ilps22qs_reg.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ilps22qs/ilps22qs_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ism330is.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism330is/ism330is.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ism330is_reg.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism330is/ism330is_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ism6hg256x.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism6hg256x/ism6hg256x.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ism6hg256x_reg.o: C:/Users/bence/Downloads/x-cube-mems1/Drivers/BSP/Components/ism6hg256x/ism6hg256x_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../../Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/Components/ism330is -I../../../../../../../Drivers/BSP/Components/ism6hg256x -I../../../../../../../Drivers/BSP/Components/ilps22qs -I../../../../../../../Drivers/BSP/Components/iis2dulpx -I../../../../../../../Drivers/BSP/Components/iis2mdc -I../../../../../../../Drivers/BSP/IKS5A1 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-Components

clean-Drivers-2f-BSP-2f-Components:
	-$(RM) ./Drivers/BSP/Components/iis2dulpx.cyclo ./Drivers/BSP/Components/iis2dulpx.d ./Drivers/BSP/Components/iis2dulpx.o ./Drivers/BSP/Components/iis2dulpx.su ./Drivers/BSP/Components/iis2dulpx_reg.cyclo ./Drivers/BSP/Components/iis2dulpx_reg.d ./Drivers/BSP/Components/iis2dulpx_reg.o ./Drivers/BSP/Components/iis2dulpx_reg.su ./Drivers/BSP/Components/iis2mdc.cyclo ./Drivers/BSP/Components/iis2mdc.d ./Drivers/BSP/Components/iis2mdc.o ./Drivers/BSP/Components/iis2mdc.su ./Drivers/BSP/Components/iis2mdc_reg.cyclo ./Drivers/BSP/Components/iis2mdc_reg.d ./Drivers/BSP/Components/iis2mdc_reg.o ./Drivers/BSP/Components/iis2mdc_reg.su ./Drivers/BSP/Components/ilps22qs.cyclo ./Drivers/BSP/Components/ilps22qs.d ./Drivers/BSP/Components/ilps22qs.o ./Drivers/BSP/Components/ilps22qs.su ./Drivers/BSP/Components/ilps22qs_reg.cyclo ./Drivers/BSP/Components/ilps22qs_reg.d ./Drivers/BSP/Components/ilps22qs_reg.o ./Drivers/BSP/Components/ilps22qs_reg.su ./Drivers/BSP/Components/ism330is.cyclo ./Drivers/BSP/Components/ism330is.d ./Drivers/BSP/Components/ism330is.o ./Drivers/BSP/Components/ism330is.su ./Drivers/BSP/Components/ism330is_reg.cyclo ./Drivers/BSP/Components/ism330is_reg.d ./Drivers/BSP/Components/ism330is_reg.o ./Drivers/BSP/Components/ism330is_reg.su ./Drivers/BSP/Components/ism6hg256x.cyclo ./Drivers/BSP/Components/ism6hg256x.d ./Drivers/BSP/Components/ism6hg256x.o ./Drivers/BSP/Components/ism6hg256x.su ./Drivers/BSP/Components/ism6hg256x_reg.cyclo ./Drivers/BSP/Components/ism6hg256x_reg.d ./Drivers/BSP/Components/ism6hg256x_reg.o ./Drivers/BSP/Components/ism6hg256x_reg.su

.PHONY: clean-Drivers-2f-BSP-2f-Components

