begin SENSOR_GLOBAL
    external_platform_library_path = /data/home/qnxuser/libsensor_platform_broadcom_rpi5.so
    external_platform_library_variant = PLATFORM_VARIANT_BCM2712
end SENSOR_GLOBAL

begin SENSOR_UNIT_1
    type = external_camera
    name = imx708
    address = /data/home/qnxuser/libimx708_external_camera.so,1
    use_hardware_capture = true
    i2c_path = /dev/i2c6
    default_video_format = nv12
end SENSOR_UNIT_1

begin INTERIM_DATA_UNIT_1
    num_buffers = 5
    buffer_size = 8096
    queue_depth = 1
    data_format = SENSOR_FORMAT_ISP_TUNING_REQUEST
    name = tuning_requests
end INTERIM_DATA_UNIT_1

begin ISP_TUNING_1
    request_interim_data_unit = INTERIM_DATA_UNIT_1
    sensor_units = SENSOR_UNIT_1
end ISP_TUNING_1
